name: TSO Function Test
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  tso-function-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Make TSO Function Test
        run: make test-tso-function
